entry1 = input(">")
entry2 = int(input(">"))
entry3 = list(input(">"))
entry4 = tuple(input(">"))
entry5 = input(">")
print("\n")
print(f"Values=> entry1: {entry1},\n\t\t entry2: {entry2},\n\t\t entry3: {entry3},\n\t\t entry4: {entry4},\n\t\t entry5: {entry5}")
print("\n")
print("Types=> entry1: {},\n\t\tentry2: {},\n\t\tentry3: {},\n\t\tentry4: {},\n\t\tentry5: {}".format(type(entry1), type(entry2), type(entry3), type(entry4), type(entry5)))
